/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvertSlot: typeof import('./src/components/AdvertSlot.vue')['default']
    AnalyticsLoader: typeof import('./src/components/AnalyticsLoader.vue')['default']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    Aside: typeof import('./src/components/Layout/Aside.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    BottomMore: typeof import('./src/components/global/BottomMore.vue')['default']
    CloseButton: typeof import('./src/components/global/CloseButton.vue')['default']
    DialogInfo: typeof import('./src/components/DialogInfo.vue')['default']
    DialogPopupAds: typeof import('./src/components/DialogPopupAds.vue')['default']
    Dropdown: typeof import('./src/components/global/Dropdown.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FollowButton: typeof import('./src/components/global/FollowButton.vue')['default']
    Footer: typeof import('./src/components/Layout/Footer.vue')['default']
    Header: typeof import('./src/components/Layout/Header.vue')['default']
    Heart: typeof import('./src/components/global/Heart.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    InstallPWA: typeof import('./src/components/global/InstallPWA.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialNetwork: typeof import('./src/components/SocialNetwork.vue')['default']
    Tinyeditor: typeof import('./src/components/Tinyeditor/index.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
